# Docker Compose Local Development Setup
#
# This starts a local multi-container development environment
# with Postgres, Redis, and Django.
# The configuration comes from .env/local and .env/postgres
#
# To run:
#   $ make dockerbuild
#   $ make dockerserve

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sandiegopython_local_django
    depends_on:
      - postgres
    env_file:
      - ./.env/local
      - ./.env/postgres
    ports:
      - "${SANDIEGOPYTHON_DJANGO_PORT:-8000}:8000"
    # Allow us to run `docker attach` and get
    # control on STDIN and be able to debug our code with interactive pdb
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15.2
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/postgres

  redis:
    image: redis:5.0
