# Generated by Django 5.2.8 on 2025-11-23 17:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pythonsd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "website_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "logo",
                    models.ImageField(
                        help_text="Recommended size of 300*300px or larger square",
                        upload_to="sponsors/",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to hide this sponsor from the sponsors page",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Sponsors are displayed in ascending order of this value",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
