# Generated by Django 5.2.16 on 2026-09-25 23:23

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pythonsd", "0002_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(db_index=True)),
                ("youtube_id", models.CharField(max_length=32, unique=True)),
                (
                    "meetup_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "timestamp_seconds",
                    models.PositiveIntegerField(help_text="Start time in seconds"),
                ),
                (
                    "timestamp_label",
                    models.CharField(
                        help_text="Timestamp as displayed on YouTube (e.g. 10:12)",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "meetup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talks",
                        to="pythonsd.meetup",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "timestamp_seconds"),
            },
        ),
    ]
